### PR TITLE
ProfileListings new PR

### PR DESCRIPTION
**Pull request by quddd**
Screen Shot 2021-01-22 at 7 50 30 AM
Screen Shot 2021-01-22 at 7 51 32 AM

### CODE REVIEW

**Comment by dproc96** [comment]
Screen Shot 2021-01-22 at 7 56 02 AM
I'm still getting this error, can you merge dev into this branch?

**Comment by quddd** [comment]
> Screen Shot 2021-01-22 at 7 56 02 AM
> 
> I'm still getting this error, can you merge dev into this branch?

I didn't commit my Nvabar file because Thomas as already created a PR to fix that so I didn't want merge conflicts

**Comment by quddd** [comment]
> Screen Shot 2021-01-22 at 7 56 02 AM
> 
> I'm still getting this error, can you merge dev into this branch?
=========================================================================================
I just merged dev and it's working

**Review by dproc96 — APPROVED** [review]
This looks good to go!

**Pull request merged**
